name: Docker push

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build app
        run: docker-compose build

      - name: Docker push
        run: docker push tmvdl/projects:nume

